### ISSUE TITLE
nzn

### ISSUE THREAD

**Issue by MartynasKasp** [MantasGra/Financify#16]
nzn sitas projektas kazkaip

**Comment by MykolasVitkus** [comment]
visai nieko manau, galima kazka gero isvystyt

**Comment by MykolasVitkus** [comment]
@MantasGra input? manau reiktu sita issue isresolvint ir mergint, nes dabar biski stabdo darba

**Comment by MykolasVitkus** [comment]
by the looks of it, no action was taken, closing this issue
